server:
  port: 8443
  compression:
    enabled: true
  http2:
    # 启用http2
    enabled: true
  ssl:
    enabled: true
    key-store: classpath:keystore.p12 # 启用http2
    key-password: 123456
    key-store-type: PKCS12
    protocol: TLSv1.2 # 协议类型
    key-alias: undertow
