spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    druid:
      username: root
      password: VisT2iiLc
      url: jdbc:mysql://47.98.186.6:3306/white_jotter?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8443

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

